name: gomuflix
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  sqflite: ^2.0.2+1
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  provider: ^6.0.3
  path_provider: ^2.0.10
  get_it: ^7.2.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/profile.png