// Mocks generated by Mockito 5.2.0 from annotations
// in gomumovie/test/presentation/screen/gomu_movie_main_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:gomucore/gomucore.dart' as _i3;
import 'package:gomumovie/gomumovie.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetGomuflixMovieListCase_0 extends _i1.Fake
    implements _i2.GetGomuflixMovieListCase {}

class _FakeGetGomuflixMovieWatchlistCase_1 extends _i1.Fake
    implements _i2.GetGomuflixMovieWatchlistCase {}

/// A class which mocks [GomuflixMovieListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGomuflixMovieListNotifier extends _i1.Mock
    implements _i2.GomuflixMovieListNotifier {
  MockGomuflixMovieListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetGomuflixMovieListCase get getNowPlayingMovies =>
      (super.noSuchMethod(Invocation.getter(#getNowPlayingMovies),
              returnValue: _FakeGetGomuflixMovieListCase_0())
          as _i2.GetGomuflixMovieListCase);
  @override
  set getNowPlayingMovies(_i2.GetGomuflixMovieListCase? _getNowPlayingMovies) =>
      super.noSuchMethod(
          Invocation.setter(#getNowPlayingMovies, _getNowPlayingMovies),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixMovieListCase get getPopularMovies =>
      (super.noSuchMethod(Invocation.getter(#getPopularMovies),
              returnValue: _FakeGetGomuflixMovieListCase_0())
          as _i2.GetGomuflixMovieListCase);
  @override
  set getPopularMovies(_i2.GetGomuflixMovieListCase? _getPopularMovies) => super
      .noSuchMethod(Invocation.setter(#getPopularMovies, _getPopularMovies),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixMovieListCase get getTopRatedMovies =>
      (super.noSuchMethod(Invocation.getter(#getTopRatedMovies),
              returnValue: _FakeGetGomuflixMovieListCase_0())
          as _i2.GetGomuflixMovieListCase);
  @override
  set getTopRatedMovies(_i2.GetGomuflixMovieListCase? _getTopRatedMovies) =>
      super.noSuchMethod(
          Invocation.setter(#getTopRatedMovies, _getTopRatedMovies),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixMovieWatchlistCase get getWatchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistMovies),
              returnValue: _FakeGetGomuflixMovieWatchlistCase_1())
          as _i2.GetGomuflixMovieWatchlistCase);
  @override
  set getWatchlistMovies(
          _i2.GetGomuflixMovieWatchlistCase? _getWatchlistMovies) =>
      super.noSuchMethod(
          Invocation.setter(#getWatchlistMovies, _getWatchlistMovies),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get nowPlayingMovieVar =>
      (super.noSuchMethod(Invocation.getter(#nowPlayingMovieVar),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set nowPlayingMovieVar(List<_i2.GomuflixMovieEntity>? _nowPlayingMovieVar) =>
      super.noSuchMethod(
          Invocation.setter(#nowPlayingMovieVar, _nowPlayingMovieVar),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get popularMovieVar =>
      (super.noSuchMethod(Invocation.getter(#popularMovieVar),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set popularMovieVar(List<_i2.GomuflixMovieEntity>? _popularMovieVar) =>
      super.noSuchMethod(Invocation.setter(#popularMovieVar, _popularMovieVar),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get topRatedMovieVar =>
      (super.noSuchMethod(Invocation.getter(#topRatedMovieVar),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set topRatedMovieVar(List<_i2.GomuflixMovieEntity>? _topRatedMovieVar) =>
      super.noSuchMethod(
          Invocation.setter(#topRatedMovieVar, _topRatedMovieVar),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get watchlistMovieVar =>
      (super.noSuchMethod(Invocation.getter(#watchlistMovieVar),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set watchlistMovieVar(List<_i2.GomuflixMovieEntity>? _watchlistMovieVar) =>
      super.noSuchMethod(
          Invocation.setter(#watchlistMovieVar, _watchlistMovieVar),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get gomuMovie =>
      (super.noSuchMethod(Invocation.getter(#gomuMovie),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set gomuMovie(List<_i2.GomuflixMovieEntity>? _gomuMovie) =>
      super.noSuchMethod(Invocation.setter(#gomuMovie, _gomuMovie),
          returnValueForMissingStub: null);
  @override
  _i3.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  set state(_i3.RequestState? _state) =>
      super.noSuchMethod(Invocation.setter(#state, _state),
          returnValueForMissingStub: null);
  @override
  String get messageVar =>
      (super.noSuchMethod(Invocation.getter(#messageVar), returnValue: '')
          as String);
  @override
  set messageVar(String? _messageVar) =>
      super.noSuchMethod(Invocation.setter(#messageVar, _messageVar),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get nowPlayingMovies =>
      (super.noSuchMethod(Invocation.getter(#nowPlayingMovies),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  List<_i2.GomuflixMovieEntity> get popularMovies =>
      (super.noSuchMethod(Invocation.getter(#popularMovies),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  List<_i2.GomuflixMovieEntity> get topRatedMovies =>
      (super.noSuchMethod(Invocation.getter(#topRatedMovies),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  List<_i2.GomuflixMovieEntity> get watchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#watchlistMovies),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  List<_i2.GomuflixMovieEntity> get movie =>
      (super.noSuchMethod(Invocation.getter(#movie),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  _i3.RequestState get gomuMovieNowPlayingState =>
      (super.noSuchMethod(Invocation.getter(#gomuMovieNowPlayingState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  _i3.RequestState get gomuMoviePopularState =>
      (super.noSuchMethod(Invocation.getter(#gomuMoviePopularState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  _i3.RequestState get gomuMovieTopRatedState =>
      (super.noSuchMethod(Invocation.getter(#gomuMovieTopRatedState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  _i3.RequestState get gomuMovieWatchlistState =>
      (super.noSuchMethod(Invocation.getter(#gomuMovieWatchlistState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<void> syncGomuMovieNowPlaying() =>
      (super.noSuchMethod(Invocation.method(#syncGomuMovieNowPlaying, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuMoviePopular() =>
      (super.noSuchMethod(Invocation.method(#syncGomuMoviePopular, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuMovieTopRated() =>
      (super.noSuchMethod(Invocation.method(#syncGomuMovieTopRated, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuMovieWatchlist() =>
      (super.noSuchMethod(Invocation.method(#syncGomuMovieWatchlist, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
