// Mocks generated by Mockito 5.2.0 from annotations
// in gomumovie/test/presentation/screen/gomu_movie_detail_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:gomucore/gomucore.dart' as _i3;
import 'package:gomumovie/gomumovie.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetGomuflixMovieDetailCase_0 extends _i1.Fake
    implements _i2.GetGomuflixMovieDetailCase {}

class _FakeGetGomuflixMovieWatchlistCase_1 extends _i1.Fake
    implements _i2.GetGomuflixMovieWatchlistCase {}

class _FakeSaveGomuflixMoviewatchlist_2 extends _i1.Fake
    implements _i2.SaveGomuflixMoviewatchlist {}

class _FakeRemoveGomuflixMoviewatchlist_3 extends _i1.Fake
    implements _i2.RemoveGomuflixMoviewatchlist {}

class _FakeGomuflixMovieDetailEntity_4 extends _i1.Fake
    implements _i2.GomuflixMovieDetailEntity {}

/// A class which mocks [GomuflixMovieDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGomuflixMovieDetailNotifier extends _i1.Mock
    implements _i2.GomuflixMovieDetailNotifier {
  MockGomuflixMovieDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetGomuflixMovieDetailCase get getGomuMovieDetail =>
      (super.noSuchMethod(Invocation.getter(#getGomuMovieDetail),
              returnValue: _FakeGetGomuflixMovieDetailCase_0())
          as _i2.GetGomuflixMovieDetailCase);
  @override
  set getGomuMovieDetail(_i2.GetGomuflixMovieDetailCase? _getGomuMovieDetail) =>
      super.noSuchMethod(
          Invocation.setter(#getGomuMovieDetail, _getGomuMovieDetail),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixMovieDetailCase get getGomuMovieRecommendation =>
      (super.noSuchMethod(Invocation.getter(#getGomuMovieRecommendation),
              returnValue: _FakeGetGomuflixMovieDetailCase_0())
          as _i2.GetGomuflixMovieDetailCase);
  @override
  set getGomuMovieRecommendation(
          _i2.GetGomuflixMovieDetailCase? _getGomuMovieRecommendation) =>
      super.noSuchMethod(
          Invocation.setter(
              #getGomuMovieRecommendation, _getGomuMovieRecommendation),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixMovieWatchlistCase get getGomuMovieWatchlistStatus =>
      (super.noSuchMethod(Invocation.getter(#getGomuMovieWatchlistStatus),
              returnValue: _FakeGetGomuflixMovieWatchlistCase_1())
          as _i2.GetGomuflixMovieWatchlistCase);
  @override
  set getGomuMovieWatchlistStatus(
          _i2.GetGomuflixMovieWatchlistCase? _getGomuMovieWatchlistStatus) =>
      super.noSuchMethod(
          Invocation.setter(
              #getGomuMovieWatchlistStatus, _getGomuMovieWatchlistStatus),
          returnValueForMissingStub: null);
  @override
  _i2.SaveGomuflixMoviewatchlist get saveGomuMovieWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveGomuMovieWatchlist),
              returnValue: _FakeSaveGomuflixMoviewatchlist_2())
          as _i2.SaveGomuflixMoviewatchlist);
  @override
  set saveGomuMovieWatchlist(
          _i2.SaveGomuflixMoviewatchlist? _saveGomuMovieWatchlist) =>
      super.noSuchMethod(
          Invocation.setter(#saveGomuMovieWatchlist, _saveGomuMovieWatchlist),
          returnValueForMissingStub: null);
  @override
  _i2.RemoveGomuflixMoviewatchlist get removeGomuMovieWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeGomuMovieWatchlist),
              returnValue: _FakeRemoveGomuflixMoviewatchlist_3())
          as _i2.RemoveGomuflixMoviewatchlist);
  @override
  set removeGomuMovieWatchlist(
          _i2.RemoveGomuflixMoviewatchlist? _removeGomuMovieWatchlist) =>
      super.noSuchMethod(
          Invocation.setter(
              #removeGomuMovieWatchlist, _removeGomuMovieWatchlist),
          returnValueForMissingStub: null);
  @override
  _i2.GomuflixMovieDetailEntity get gomuMovieEntity =>
      (super.noSuchMethod(Invocation.getter(#gomuMovieEntity),
              returnValue: _FakeGomuflixMovieDetailEntity_4())
          as _i2.GomuflixMovieDetailEntity);
  @override
  set gomuMovieEntity(_i2.GomuflixMovieDetailEntity? _gomuMovieEntity) =>
      super.noSuchMethod(Invocation.setter(#gomuMovieEntity, _gomuMovieEntity),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixMovieEntity> get movieRecommendationsVar =>
      (super.noSuchMethod(Invocation.getter(#movieRecommendationsVar),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  set movieRecommendationsVar(
          List<_i2.GomuflixMovieEntity>? _movieRecommendationsVar) =>
      super.noSuchMethod(
          Invocation.setter(#movieRecommendationsVar, _movieRecommendationsVar),
          returnValueForMissingStub: null);
  @override
  _i3.RequestState get stateVar =>
      (super.noSuchMethod(Invocation.getter(#stateVar),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  set stateVar(_i3.RequestState? _stateVar) =>
      super.noSuchMethod(Invocation.setter(#stateVar, _stateVar),
          returnValueForMissingStub: null);
  @override
  String get messageVar =>
      (super.noSuchMethod(Invocation.getter(#messageVar), returnValue: '')
          as String);
  @override
  set messageVar(String? _messageVar) =>
      super.noSuchMethod(Invocation.setter(#messageVar, _messageVar),
          returnValueForMissingStub: null);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  _i2.GomuflixMovieDetailEntity get movie =>
      (super.noSuchMethod(Invocation.getter(#movie),
              returnValue: _FakeGomuflixMovieDetailEntity_4())
          as _i2.GomuflixMovieDetailEntity);
  @override
  List<_i2.GomuflixMovieEntity> get movieRecommendations =>
      (super.noSuchMethod(Invocation.getter(#movieRecommendations),
              returnValue: <_i2.GomuflixMovieEntity>[])
          as List<_i2.GomuflixMovieEntity>);
  @override
  _i3.RequestState get movieState =>
      (super.noSuchMethod(Invocation.getter(#movieState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  _i3.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<void> syncGomuMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#syncGomuMovieDetail, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuMovieAddWatchlist(
          _i2.GomuflixMovieDetailEntity? movie) =>
      (super.noSuchMethod(
          Invocation.method(#syncGomuMovieAddWatchlist, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuMovieRemoveWatchlist(
          _i2.GomuflixMovieDetailEntity? movie) =>
      (super.noSuchMethod(
          Invocation.method(#syncGomuMovieRemoveWatchlist, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
