// Mocks generated by Mockito 5.2.0 from annotations
// in gomutv/test/presentation/screen/gomu_tv_detail_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:gomucore/gomucore.dart' as _i3;
import 'package:gomutv/gomutv.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetGomuflixTvDetailCase_0 extends _i1.Fake
    implements _i2.GetGomuflixTvDetailCase {}

class _FakeGetGomuflixTvWatchlistCase_1 extends _i1.Fake
    implements _i2.GetGomuflixTvWatchlistCase {}

class _FakeSaveGomuflixTvWatchlistCase_2 extends _i1.Fake
    implements _i2.SaveGomuflixTvWatchlistCase {}

class _FakeRemoveGomuflixTvWatchlistCase_3 extends _i1.Fake
    implements _i2.RemoveGomuflixTvWatchlistCase {}

class _FakeGomuflixTvDetailEntity_4 extends _i1.Fake
    implements _i2.GomuflixTvDetailEntity {}

/// A class which mocks [GomuflixTvDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockGomuflixTvDetailNotifier extends _i1.Mock
    implements _i2.GomuflixTvDetailNotifier {
  MockGomuflixTvDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetGomuflixTvDetailCase get getGomuTvDetail =>
      (super.noSuchMethod(Invocation.getter(#getGomuTvDetail),
              returnValue: _FakeGetGomuflixTvDetailCase_0())
          as _i2.GetGomuflixTvDetailCase);
  @override
  set getGomuTvDetail(_i2.GetGomuflixTvDetailCase? _getGomuTvDetail) =>
      super.noSuchMethod(Invocation.setter(#getGomuTvDetail, _getGomuTvDetail),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixTvDetailCase get getGomuTvRecommendation =>
      (super.noSuchMethod(Invocation.getter(#getGomuTvRecommendation),
              returnValue: _FakeGetGomuflixTvDetailCase_0())
          as _i2.GetGomuflixTvDetailCase);
  @override
  set getGomuTvRecommendation(
          _i2.GetGomuflixTvDetailCase? _getGomuTvRecommendation) =>
      super.noSuchMethod(
          Invocation.setter(#getGomuTvRecommendation, _getGomuTvRecommendation),
          returnValueForMissingStub: null);
  @override
  _i2.GetGomuflixTvWatchlistCase get getGomuTvWatchlistStatus =>
      (super.noSuchMethod(Invocation.getter(#getGomuTvWatchlistStatus),
              returnValue: _FakeGetGomuflixTvWatchlistCase_1())
          as _i2.GetGomuflixTvWatchlistCase);
  @override
  set getGomuTvWatchlistStatus(
          _i2.GetGomuflixTvWatchlistCase? _getGomuTvWatchlistStatus) =>
      super.noSuchMethod(
          Invocation.setter(
              #getGomuTvWatchlistStatus, _getGomuTvWatchlistStatus),
          returnValueForMissingStub: null);
  @override
  _i2.SaveGomuflixTvWatchlistCase get saveGomuTvWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveGomuTvWatchlist),
              returnValue: _FakeSaveGomuflixTvWatchlistCase_2())
          as _i2.SaveGomuflixTvWatchlistCase);
  @override
  set saveGomuTvWatchlist(
          _i2.SaveGomuflixTvWatchlistCase? _saveGomuTvWatchlist) =>
      super.noSuchMethod(
          Invocation.setter(#saveGomuTvWatchlist, _saveGomuTvWatchlist),
          returnValueForMissingStub: null);
  @override
  _i2.RemoveGomuflixTvWatchlistCase get removeGomuTvWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeGomuTvWatchlist),
              returnValue: _FakeRemoveGomuflixTvWatchlistCase_3())
          as _i2.RemoveGomuflixTvWatchlistCase);
  @override
  set removeGomuTvWatchlist(
          _i2.RemoveGomuflixTvWatchlistCase? _removeGomuTvWatchlist) =>
      super.noSuchMethod(
          Invocation.setter(#removeGomuTvWatchlist, _removeGomuTvWatchlist),
          returnValueForMissingStub: null);
  @override
  _i2.GomuflixTvDetailEntity get gomuTvEntitiy =>
      (super.noSuchMethod(Invocation.getter(#gomuTvEntitiy),
              returnValue: _FakeGomuflixTvDetailEntity_4())
          as _i2.GomuflixTvDetailEntity);
  @override
  set gomuTvEntitiy(_i2.GomuflixTvDetailEntity? _gomuTvEntitiy) =>
      super.noSuchMethod(Invocation.setter(#gomuTvEntitiy, _gomuTvEntitiy),
          returnValueForMissingStub: null);
  @override
  List<_i2.GomuflixTvEntity> get gomuTvRecommendation =>
      (super.noSuchMethod(Invocation.getter(#gomuTvRecommendation),
          returnValue: <_i2.GomuflixTvEntity>[]) as List<_i2.GomuflixTvEntity>);
  @override
  set gomuTvRecommendation(List<_i2.GomuflixTvEntity>? _gomuTvRecommendation) =>
      super.noSuchMethod(
          Invocation.setter(#gomuTvRecommendation, _gomuTvRecommendation),
          returnValueForMissingStub: null);
  @override
  _i3.RequestState get stateVar =>
      (super.noSuchMethod(Invocation.getter(#stateVar),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  set stateVar(_i3.RequestState? _stateVar) =>
      super.noSuchMethod(Invocation.setter(#stateVar, _stateVar),
          returnValueForMissingStub: null);
  @override
  String get messageVar =>
      (super.noSuchMethod(Invocation.getter(#messageVar), returnValue: '')
          as String);
  @override
  set messageVar(String? _messageVar) =>
      super.noSuchMethod(Invocation.setter(#messageVar, _messageVar),
          returnValueForMissingStub: null);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  _i2.GomuflixTvDetailEntity get tv =>
      (super.noSuchMethod(Invocation.getter(#tv),
              returnValue: _FakeGomuflixTvDetailEntity_4())
          as _i2.GomuflixTvDetailEntity);
  @override
  List<_i2.GomuflixTvEntity> get tvRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendations),
          returnValue: <_i2.GomuflixTvEntity>[]) as List<_i2.GomuflixTvEntity>);
  @override
  _i3.RequestState get tvState =>
      (super.noSuchMethod(Invocation.getter(#tvState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  _i3.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i3.RequestState.empty) as _i3.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<void> syncGomuTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#syncGomuTvDetail, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuTvAddWatchlist(_i2.GomuflixTvDetailEntity? tv) =>
      (super.noSuchMethod(Invocation.method(#syncGomuTvAddWatchlist, [tv]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> syncGomuTvRemoveWatchlist(_i2.GomuflixTvDetailEntity? tv) =>
      (super.noSuchMethod(Invocation.method(#syncGomuTvRemoveWatchlist, [tv]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
