name: gomutv
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  gomucore:
    path: ../gomucore
  gomumovie:
    path: ../gomumovie
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.3
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
