name: gomucore
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  gomumovie:
    path: ../gomumovie
  gomutv:
    path: ../gomutv
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  equatable: ^2.0.2
  google_fonts: ^3.0.1
  provider: ^6.0.3
  path_provider: ^2.0.10
  get_it: ^7.2.0
  bloc: ^8.0.0
  flutter_bloc: ^8.0.1
  firebase_crashlytics: ^2.8.1



dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter

flutter:
